/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.SerieDAO;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import modelo.Serie;

/**
 *
 * @author admin
 */
public class frmConfiguracion extends javax.swing.JFrame {
    //objetos para la serie 

    Serie objSerie = new Serie();
    SerieDAO objSerieDAO = new SerieDAO();

    /**
     * Creates new form frmConfiguracion
     */
    public frmConfiguracion() {
        initComponents();

        frmVenta objFrmVenta = new frmVenta();
        //asina el numero de serie factura a la txtSerieConfCF
        txtSerieConfCF.setText(objFrmVenta.obtenerserie(1));
        //asina el numero de serie ccf a la txtSerieConfCC
        txtSerieConfCC.setText(objFrmVenta.obtenerserie(2));
         //asina el ancho factura
        txtAnchoCF.setText(objFrmVenta.obtenerAncho(1));
        //asina el ancho ccf
        txtAnchoCC.setText(objFrmVenta.obtenerAncho(2));
    }

    public void establecerSerie(int tipo) {

        try {

            String seriecf = txtSerieConfCF.getText();
            String anchocc = txtSerieConfCC.getText();

            if (!(seriecf.isEmpty() || anchocc.isEmpty())) {
                objSerie.setNumeroSeriefact(seriecf);
                objSerie.setNumeroSerieccf(anchocc);
                try {
                    objSerieDAO.modificarSerie(objSerie, tipo);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Algo salio mal " + e, "Error",
                            JOptionPane.ERROR_MESSAGE);

                }
            }
        } catch (HeadlessException e) {

        }

    }
        public void establecerAncho(int tipo) {

        try {
            String s_anchocf = txtAnchoCF.getText().trim();
            String s_serirecc = txtAnchoCC.getText().trim();
            int anchocf = Integer.parseInt(s_anchocf);
            int serirecc = Integer.parseInt(s_serirecc);
          

            if (!(s_anchocf.isBlank()|| s_serirecc.isBlank())) {
                objSerie.setAnchocf(anchocf);
                objSerie.setAnchocc(serirecc);
                try {
                    objSerieDAO.modificarAncho(objSerie, tipo);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Algo salio mal " + e, "Error",
                            JOptionPane.ERROR_MESSAGE);

                }
            }
        } catch (HeadlessException e) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSerieConfCF = new javax.swing.JTextField();
        txtSerieConfCC = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAnchoCF = new javax.swing.JFormattedTextField();
        txtAnchoCC = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ESTABLECER SERIE PARA FACTURAS DE CONSUMIDOR FINAL");

        jLabel2.setText("ESTABLECER SERIE PARA COMPROBANTRES DE CREDITO FISCAL  ");

        txtSerieConfCF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerieConfCFActionPerformed(evt);
            }
        });

        jButton1.setText("GUARDAR Y SALIR  ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("CONFIGURACION ");

        jLabel4.setText("ESTABLECER EL ANCHO DE IMPRESION PARA FACTURAS ");

        jLabel5.setText("ESTABLECER  ANCHO DE IMPRESION  PARA COMPROBANTES DE CREDITOFISCAL  ");

        try {
            txtAnchoCF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAnchoCF.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        try {
            txtAnchoCC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAnchoCC.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(txtSerieConfCF, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(txtSerieConfCC, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAnchoCC, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(txtAnchoCF, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(txtSerieConfCF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSerieConfCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtAnchoCF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtAnchoCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 570, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSerieConfCFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerieConfCFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerieConfCFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        establecerSerie(1);// establece el numero de serie para la factura 
        establecerSerie(2);// establece el numero de serie para el ccf 
        establecerAncho(1);
        establecerAncho(2);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConfiguracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField txtAnchoCC;
    private javax.swing.JFormattedTextField txtAnchoCF;
    private javax.swing.JTextField txtSerieConfCC;
    private javax.swing.JTextField txtSerieConfCF;
    // End of variables declaration//GEN-END:variables

}
