/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.DetalleDAO;
import controlador.VentaDAO;
import javax.swing.table.DefaultTableModel;
import modelo.Venta;

/**
 *
 * @author admin
 */
public class frmDetalleComprobante extends javax.swing.JFrame {

    String correlativoOld, serieOld;
    VentaDAO objVentaDAO = new VentaDAO();
    DetalleDAO objDetalleDAO = new DetalleDAO();
    DefaultTableModel modelo;
    Double total = 0.00;
    String montoEnLetra = "";
    Venta objVenta = new Venta();

    /**
     * Creates new form frmDetalleComprobante
     */
    public frmDetalleComprobante(String serie, String correlativo) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);// modo pantalla Completa 
        serieOld = serie;
        correlativoOld = correlativo;
//        verEncavezadoVenta();
//        verDetalle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventaCC = new javax.swing.JPanel();
        cc_txtNombre = new javax.swing.JTextField();
        cc_txtDui = new javax.swing.JTextField();
        cc_txtNombreNegocio = new javax.swing.JTextField();
        cc_txtDireccion = new javax.swing.JTextField();
        cc_txtNoRegistro = new javax.swing.JTextField();
        cc_txtNit = new javax.swing.JTextField();
        cc_txtGiro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cc_txtCorrelativoCC = new javax.swing.JTextField();
        cc_txtSerieCC = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        cc_tableVentaCC = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cc_lbltotal = new javax.swing.JLabel();
        cc_lblIva = new javax.swing.JLabel();
        cc_lblSumas = new javax.swing.JLabel();
        btnImprimir1 = new javax.swing.JButton();
        btnAnular1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnActualizar1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblFechaRegistrada = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblFecha_eqiqueta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DETALLE COMPROBANTE DE CREDITO FISCAL");

        ventaCC.setBackground(new java.awt.Color(255, 255, 255));

        cc_txtNombre.setEditable(false);

        cc_txtDui.setEditable(false);

        cc_txtNombreNegocio.setEditable(false);

        cc_txtDireccion.setEditable(false);

        cc_txtNoRegistro.setEditable(false);

        cc_txtNit.setEditable(false);

        cc_txtGiro.setEditable(false);

        jLabel1.setText("NOMBRE");

        jLabel2.setText("GIRO");

        jLabel3.setText("REGISTRO FISCAL");

        jLabel4.setText("DIRECCION");

        jLabel5.setText("NOMBRE DE NEGOCIO ");

        jLabel16.setText("DUI");

        jLabel17.setText("NIT");

        jLabel21.setText("SERIE");

        cc_txtCorrelativoCC.setEditable(false);
        cc_txtCorrelativoCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        cc_txtSerieCC.setEditable(false);

        jLabel52.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(102, 0, 0));
        jLabel52.setText("DETALLE COMPROBANTE DE CREDITO FISCAL");

        cc_tableVentaCC.setForeground(new java.awt.Color(51, 102, 255));
        cc_tableVentaCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM", "CODIGO", "DESCRIPCION", "CANTIDAD", "UNIDAD DE MEDIDA", "PRECIO UNITARIO", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cc_tableVentaCC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cc_tableVentaCC.setGridColor(new java.awt.Color(255, 255, 255));
        cc_tableVentaCC.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cc_tableVentaCCPropertyChange(evt);
            }
        });
        jScrollPane4.setViewportView(cc_tableVentaCC);

        jLabel22.setText("CORRELATIVO");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));

        jLabel28.setText("SUMAS");

        jLabel27.setText("IVA ");

        jLabel26.setText("TOTAL");

        cc_lbltotal.setText("0.00");

        cc_lblIva.setText("0.00");

        cc_lblSumas.setText("0.00");

        btnImprimir1.setText("IMPRIMIR");
        btnImprimir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir1ActionPerformed(evt);
            }
        });

        btnAnular1.setForeground(new java.awt.Color(153, 0, 0));
        btnAnular1.setText("ANULAR");

        btnEliminar1.setForeground(new java.awt.Color(153, 0, 0));
        btnEliminar1.setText("ANULAR Y ELIMINAR");

        btnActualizar1.setText("ACTUALIZAR");
        btnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btnImprimir1)
                .addGap(138, 138, 138)
                .addComponent(btnAnular1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(btnEliminar1)
                .addGap(123, 123, 123)
                .addComponent(btnActualizar1)
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cc_lblIva, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cc_lblSumas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cc_lbltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizar1)
                            .addComponent(btnEliminar1)
                            .addComponent(btnAnular1)
                            .addComponent(btnImprimir1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(cc_lblSumas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(cc_lblIva))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(cc_lbltotal))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel6.setText("ESTADO");

        jLabel7.setText("FECHA REGISTRADA");

        lblFechaRegistrada.setText("_____");

        lblEstado.setText("------");

        jDateChooser1.setVisible(false);

        lblFecha_eqiqueta.setText("FECHA ");
        lblFecha_eqiqueta.setVisible(false);

        javax.swing.GroupLayout ventaCCLayout = new javax.swing.GroupLayout(ventaCC);
        ventaCC.setLayout(ventaCCLayout);
        ventaCCLayout.setHorizontalGroup(
            ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventaCCLayout.createSequentialGroup()
                .addGap(525, 525, 525)
                .addComponent(jLabel52)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ventaCCLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventaCCLayout.createSequentialGroup()
                        .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(42, 42, 42)
                        .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cc_txtNit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(cc_txtNoRegistro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cc_txtDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cc_txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cc_txtDui, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cc_txtNombreNegocio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cc_txtGiro))
                        .addGap(259, 259, 259)
                        .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ventaCCLayout.createSequentialGroup()
                                .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(lblFecha_eqiqueta))
                                .addGap(18, 18, 18)
                                .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cc_txtCorrelativoCC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cc_txtSerieCC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ventaCCLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(lblFechaRegistrada))
                            .addGroup(ventaCCLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblEstado)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventaCCLayout.createSequentialGroup()
                        .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))
                        .addGap(87, 87, 87))))
        );
        ventaCCLayout.setVerticalGroup(
            ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventaCCLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel52)
                .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventaCCLayout.createSequentialGroup()
                        .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ventaCCLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(lblFechaRegistrada))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21))
                            .addGroup(ventaCCLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(cc_txtSerieCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cc_txtCorrelativoCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventaCCLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cc_txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(lblEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cc_txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cc_txtNombreNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cc_txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cc_txtNoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(cc_txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(ventaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cc_txtGiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblFecha_eqiqueta)))
                        .addGap(60, 60, 60)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ventaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventaCC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cc_tableVentaCCPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cc_tableVentaCCPropertyChange
        // TODO add your handling code here:
   
    }//GEN-LAST:event_cc_tableVentaCCPropertyChange

    private void btnImprimir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir1ActionPerformed
       
    }//GEN-LAST:event_btnImprimir1ActionPerformed

    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnActualizar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDetalleComprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDetalleComprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDetalleComprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDetalleComprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDetalleComprobante("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar1;
    private javax.swing.JButton btnAnular1;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnImprimir1;
    private javax.swing.JLabel cc_lblIva;
    private javax.swing.JLabel cc_lblSumas;
    private javax.swing.JLabel cc_lbltotal;
    private javax.swing.JTable cc_tableVentaCC;
    private javax.swing.JTextField cc_txtCorrelativoCC;
    private javax.swing.JTextField cc_txtDireccion;
    private javax.swing.JTextField cc_txtDui;
    private javax.swing.JTextField cc_txtGiro;
    private javax.swing.JTextField cc_txtNit;
    private javax.swing.JTextField cc_txtNoRegistro;
    private javax.swing.JTextField cc_txtNombre;
    private javax.swing.JTextField cc_txtNombreNegocio;
    private javax.swing.JTextField cc_txtSerieCC;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechaRegistrada;
    private javax.swing.JLabel lblFecha_eqiqueta;
    private javax.swing.JPanel ventaCC;
    // End of variables declaration//GEN-END:variables
}
