/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ProductoDAO;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;

/**
 *
 * @author admin
 */
public class frmSeleccionarProducto extends javax.swing.JFrame {

    String ProductoArray[];

    ProductoDAO objProductoDAO = new ProductoDAO();
    DefaultTableModel modelo;

    public String idproducto = " ", nombre = " ";

    /**
     * Creates new form frmSeleccionarProducto
     */
    public frmSeleccionarProducto() {

        initComponents();

        // lleno la tabla para que no de error cuando este vacia e intente limpiar el moelo 
        txtBuscarProducto.setText("");
        listarProductoSimilares();

    }

    public void listarProductoSimilares() {
        String nombre_1 = txtBuscarProducto.getText();
        List<Producto> listarProd = objProductoDAO.buscarProductosSimilares(nombre_1);
        modelo = (DefaultTableModel) tableProdcuto.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i < listarProd.size(); i++) {

            ob[0] = listarProd.get(i).getIdproducto();
            ob[1] = listarProd.get(i).getNombre();
            ob[2] = listarProd.get(i).getPrecioCaja();
            ob[3] = listarProd.get(i).getPrecioUnidad();
            ob[4] = listarProd.get(i).getExistencia();
            modelo.addRow(ob);
        }

        tableProdcuto.setModel(modelo);
    }

    public void limpiar_tableProductoCF() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
              i --; 
        }
    }

    public Boolean SeleccionarRegistro() {
        int row = tableProdcuto.getSelectedRow();
        String existencia = String.valueOf(tableProdcuto.getValueAt(row, 4));
        Double existencia_double = Double.valueOf(existencia);
        if (existencia_double <= 0) {

            JOptionPane.showMessageDialog(null, "El producto no puede ser seleccionado, \nLa existencia es igual o menor a cero");
            return false; // si la existencia es menor o igual a cero devuelve false 
        } else {
            idproducto = String.valueOf(modelo.getValueAt(tableProdcuto.getSelectedRow(), 0));
            return true; // si el producto es selccionable devuelve true 
        }
    }

    public void SeleccionarRegistroporCodigo(String idproducto) {
        //Consulta la infop del producto 

        ProductoArray = objProductoDAO.todoElproductoporCodigo(idproducto);   //conexion al controlador 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSeleccionarProd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtBuscarProducto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProdcuto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SELECCIONAR PRODUCTO");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("PRODUCTO");

        jLabel2.setText("SELECCIONAR PRODUCTO ");

        btnSeleccionarProd.setText("SELECCIONAR ");
        btnSeleccionarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarProdActionPerformed(evt);
            }
        });
        btnSeleccionarProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSeleccionarProdKeyPressed(evt);
            }
        });

        jButton2.setText("CANCELAR ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtBuscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarProductoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSeleccionarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(168, 168, 168))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSeleccionarProd)
                    .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(19, 19, 19))
        );

        tableProdcuto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRIPCION", "PRECIO CAJA ", "PRECIO UNITARIO ", "EXISTENCIA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProdcuto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableProdcutoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableProdcuto);
        if (tableProdcuto.getColumnModel().getColumnCount() > 0) {
            tableProdcuto.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProductoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limpiar_tableProductoCF();
            listarProductoSimilares();
            if (tableProdcuto != null && tableProdcuto.getRowCount() > 0) {
                //btnSeleccionarProd.requestFocus();
                tableProdcuto.requestFocus();
                tableProdcuto.changeSelection(0, 0, false, false);// selecciona la primera liena 
            }
        }
    }//GEN-LAST:event_txtBuscarProductoKeyPressed

    private void btnSeleccionarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarProdActionPerformed
        // TODO add your handling code here:
        int row = tableProdcuto.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "ELIJA PRIMERO UN REGISTRO , SELECCIONE UNA FILA  ", "ERROR ", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // AGARRO ELCODIGO 
        if (SeleccionarRegistro()) {
            SeleccionarRegistroporCodigo(idproducto); // OBTENGO LA INFO DEL PRODUCTO 
            this.dispose(); //CIERRO 

        } else {

        }


    }//GEN-LAST:event_btnSeleccionarProdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSeleccionarProdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSeleccionarProdKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int row = tableProdcuto.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(null, "ELIJA PRIMERO UN REGISTRO , SELECCIONE UNA FILA  ", "ERROR ", JOptionPane.WARNING_MESSAGE);
                return;
            }
            SeleccionarRegistro();
            this.dispose();
        }


    }//GEN-LAST:event_btnSeleccionarProdKeyPressed

    private void tableProdcutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableProdcutoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int row = tableProdcuto.getSelectedRow();
            if (row == -1) {

                JOptionPane.showMessageDialog(null, "ELIJA PRIMERO UN REGISTRO , SELECCIONE UNA FILA  ", "ERROR ", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // AGARRO ELCODIGO 
            if (SeleccionarRegistro()) {
                SeleccionarRegistroporCodigo(idproducto); // OBTENGO LA INFO DEL PRODUCTO 
                this.dispose(); //CIERRO 

            } else {

            }

        }
    }//GEN-LAST:event_tableProdcutoKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        txtBuscarProducto.setText("");
        limpiar_tableProductoCF();
        listarProductoSimilares();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSeleccionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSeleccionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSeleccionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSeleccionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSeleccionarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionarProd;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProdcuto;
    private javax.swing.JTextField txtBuscarProducto;
    // End of variables declaration//GEN-END:variables
}
