/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ClienteCCDAO;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ClienteCC;

/**
 *
 * @author admin
 */
public class frmSeleccionarClienteCC extends javax.swing.JFrame {

    // objetos para el clienteCC
    ClienteCCDAO objClienteCCDAO = new ClienteCCDAO();

    DefaultTableModel modelo; // modelo para tabla de seleccionar clente
     String noRegistro = " ";


    
    

    /**
     * Creates new form frmSeleccionarClienteCC
     */
    public frmSeleccionarClienteCC() {
        initComponents();
        txtBuscarNombreCC.setText("");
        listarClienteSimilares();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableClienteSCF = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnSelectClientCC = new javax.swing.JButton();
        btnCancelarCC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarNombreCC = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableClienteSCC = new javax.swing.JTable();

        tableClienteSCF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DUI", "NOMBRE", "NEGOCIO", "DIRECCION", "NIT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableClienteSCF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableClienteSCFKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableClienteSCF);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SLECCIONAR CLIENTE ");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnSelectClientCC.setText("SELECCIONAR");
        btnSelectClientCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectClientCCActionPerformed(evt);
            }
        });

        btnCancelarCC.setText("CANCELAR");
        btnCancelarCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCCActionPerformed(evt);
            }
        });

        jLabel1.setText("NOMBRE");

        jLabel2.setText("SELECCIONAR CLIENTE CON TARJETA DE IVA ");

        txtBuscarNombreCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarNombreCCKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarNombreCC, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelarCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSelectClientCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelectClientCC)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarNombreCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelarCC)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tableClienteSCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO. REGISTRO ", "NOMBRE", "DIRECCION", "NIT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableClienteSCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableClienteSCCKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tableClienteSCC);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectClientCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectClientCCActionPerformed
        // TODO add your handling code here:
        int row = tableClienteSCC.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "ELIJA PRIMERO UN REGISTRO , SELECCIONE UNA FILA  ", "ERROR ", JOptionPane.WARNING_MESSAGE);
            return;
        }
        SeleccionarRegistro();
        this.dispose();

    }//GEN-LAST:event_btnSelectClientCCActionPerformed

    private void btnCancelarCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCCActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarCCActionPerformed

    private void txtBuscarNombreCCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarNombreCCKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limpiar_tableClienteSCC();
            listarClienteSimilares();

            if (tableClienteSCC != null && tableClienteSCC.getRowCount() > 0) {
                //btnSeleccionarProd.requestFocus();
                tableClienteSCC.requestFocus();
                tableClienteSCC.changeSelection(0, 0, false, false);// selecciona la primera liena
            }
        }
    }//GEN-LAST:event_txtBuscarNombreCCKeyPressed

    private void tableClienteSCFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableClienteSCFKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int row = tableClienteSCF.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(null, "ELIJA PRIMERO UN REGISTRO , SELECCIONE UNA FILA  ", "ERROR ", JOptionPane.WARNING_MESSAGE);
                return;
            }
            SeleccionarRegistro();
            this.dispose();// AGARRO ELCODIGO
        }
    }//GEN-LAST:event_tableClienteSCFKeyPressed

    private void tableClienteSCCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableClienteSCCKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int row = tableClienteSCC.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(null, "ELIJA PRIMERO UN REGISTRO , SELECCIONE UNA FILA  ", "ERROR ", JOptionPane.WARNING_MESSAGE);
                return;
            }
            SeleccionarRegistro();
            this.dispose();// AGARRO ELCODIGO
        }
    }//GEN-LAST:event_tableClienteSCCKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        txtBuscarNombreCC.requestFocus();
        txtBuscarNombreCC.setText("");
         limpiar_tableClienteSCC();
        listarClienteSimilares();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSeleccionarClienteCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSeleccionarClienteCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSeleccionarClienteCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSeleccionarClienteCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSeleccionarClienteCC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCC;
    private javax.swing.JButton btnSelectClientCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableClienteSCC;
    private javax.swing.JTable tableClienteSCF;
    private javax.swing.JTextField txtBuscarNombreCC;
    // End of variables declaration//GEN-END:variables

    private void SeleccionarRegistro() {
          noRegistro = String.valueOf(modelo.getValueAt(tableClienteSCC.getSelectedRow(), 0));
    }

    private void limpiar_tableClienteSCC() {
         for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i--;
         }
    }

    private void listarClienteSimilares() {
        String nombre = txtBuscarNombreCC.getText();
        List<ClienteCC> listarCl = objClienteCCDAO.buscarNombresSimilares(nombre); // conexio BD
        modelo = (DefaultTableModel) tableClienteSCC.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < listarCl.size(); i++) {

            ob[0] = listarCl.get(i).getDui();
            ob[1] = listarCl.get(i).getNombre();ob[2] = listarCl.get(i).getNombreNegocio();
            ob[2] = listarCl.get(i).getDireccion();
            ob[3] = listarCl.get(i).getNit();
            modelo.addRow(ob);
        }

        tableClienteSCC.setModel(modelo);

    }
}
